### ISSUE TITLE
Unexpected error caused by ESLint validator

### ISSUE THREAD

**Issue by dpordomingo** [src-d/platform-starter#6]
I had to (manually) remove the ESLint validations from the `pre-commit` hook to workaround the following error when commiting:

```
[object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Error: [object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

    at validateConfigSchema (/usr/local/share/.config/yarn/global/node_modules/eslint/lib/config/config-validator.js:192:15)
    at Object.validate (/usr/local/share/.config/yarn/global/node_modules/eslint/lib/config/config-validator.js:205:5)
    at loadFromDisk (/usr/local/share/.config/yarn/global/node_modules/eslint/lib/config/config-file.js:549:19)
    at Object.load (/usr/local/share/.config/yarn/global/node_modules/eslint/lib/config/config-file.js:592:20)
    at Config.loadSpecificConfig (/usr/local/share/.config/yarn/global/node_modules/eslint/lib/config.js:139:46)
    at new Config (/usr/local/share/.config/yarn/global/node_modules/eslint/lib/config.js:101:14)
    at new CLIEngine (/usr/local/share/.config/yarn/global/node_modules/eslint/lib/cli-engine.js:428:23)
    at Object.execute (/usr/local/share/.config/yarn/global/node_modules/eslint/lib/cli.js:179:28)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/eslint/bin/eslint.js:72:28)
    at Module._compile (module.js:570:32)
Errors found according to eslint configuration, aborting commit.
```

Should I fix something?
I just followed the `README` of this repo... It should be maybe updated with extra guides... or maybe something should be fixed.

Any idea?

**Comment by erizocosmico** [comment]
We have no "ecmaFeatures" property anywhere: https://github.com/src-d/platform-starter/blob/master/config/.eslintrc.js

Try updating eslint?

**Comment by dpordomingo** [comment]
My `.eslintrc.js` file content was already the same than pointed by you, but it cries about `ecmaFeatures`
I'll try to dig a bit more...
quite weird

**Comment by dpordomingo** [comment]
found the problem:
```for eslint_config in $(find . -name '.eslintrc.js'); do```

finds the following:
```
./.eslintrc.js
./node_modules/domain-browser/.eslintrc.js
```
So it tries to lint (in this case, with `ecmaFeatures`) files under `node_modules` what is not desited at all.

It should be linted **only files about to be commited**.
